### ISSUE TITLE
go-lxc fails to build: error: unknown type name 'lxc_groups_t'

### ISSUE THREAD

**Issue by vrubiolo** [Drachenfels-GmbH/crio-lxc#6]
Hi there,

I am attempting to follow the installation instructions on Debian 10 but this fails during the `crio-lxc` build with the following error:
```
$ sudo make install 2>&1 | tee ~/crio-lxc-build-failure.txt
go fmt ./...
go: finding gopkg.in/lxc/go-lxc.v2 v2.0.0
go build -a -ldflags '-X main.version=v0.9.5-0-g8629c80' -o crio-lxc ./cmd
go: finding gopkg.in/lxc/go-lxc.v2 v2.0.0
# gopkg.in/lxc/go-lxc.v2
/root/go/pkg/mod/github.com/!drachenfels-!gmb!h/go-lxc@v0.0.0-20201106192530-079aead12fef/container.go:1299:13: could not determine kind of name for C.go_lxc_attach
/root/go/pkg/mod/github.com/!drachenfels-!gmb!h/go-lxc@v0.0.0-20201106192530-079aead12fef/container.go:1435:13: could not determine kind of name for C.go_lxc_attach_no_wait
/root/go/pkg/mod/github.com/!drachenfels-!gmb!h/go-lxc@v0.0.0-20201106192530-079aead12fef/container.go:1362:13: could not determine kind of name for C.go_lxc_attach_run_wait
cgo: 
gcc errors for preamble:
In file included from /root/go/pkg/mod/github.com/!drachenfels-!gmb!h/go-lxc@v0.0.0-20201106192530-079aead12fef/container.go:11:
./lxc-binding.h:59:25: error: unknown type name 'lxc_groups_t'
   uid_t uid, gid_t gid, lxc_groups_t groups,
                         ^~~~~~~~~~~~
./lxc-binding.h:69:25: error: unknown type name 'lxc_groups_t'
   uid_t uid, gid_t gid, lxc_groups_t groups,
                         ^~~~~~~~~~~~
./lxc-binding.h:78:25: error: unknown type name 'lxc_groups_t'
   uid_t uid, gid_t gid, lxc_groups_t groups,
                         ^~~~~~~~~~~~
```

I suspect this is because the version of lxc that the build finds is not recent enough. I have however followed the steps to install lxc from source, albeit modified to be used w/ `sudo`:
```sh
git clone https://github.com/lxc/lxc.git
cd lxc
./autogen.sh
./configure --enable-bash=no --enable-tools=no \
  --enable-commands=no --enable-seccomp=yes \
  --enable-capabilities=yes --enable-apparmor=yes
sudo make install

echo /usr/local/lib | sudo tee /etc/ld.so.conf.d/local.conf
sudo ldconfig
```

cf https://github.com/vrubiolo/crio-lxc/commit/2fb61453176a8e345628641aaa36f044d8447689

Full log at [crio-lxc-build-failure.txt](https://github.com/Drachenfels-GmbH/crio-lxc/files/5845699/crio-lxc-build-failure.txt)

Could you advise on what could be wrong here? Thanks much!

**Comment by vrubiolo** [comment]
Ok, it looks like the problem might come from the `LXC_VERSION_AT_LEAST` macro in https://github.com/Drachenfels-GmbH/go-lxc/blob/v2/lxc-binding.h#L49 which returns 1 in case `LXC_DEVEL` is set.

When I look at my clone of the `lxc` repo, I see matches for `LXC_DEVEL=1`. From what I understand, this could prevent the `typedef` for `lxc_structs` from being defined, causing the build error.

Removing the macro check (and thus always defining `lxc_groups_t` allows me to go past this build error (still seeing some others though, investigating).

**Comment by r10r** [comment]
hi, yes please use latest go from golang.org. I'm currently using *go version go1.15.2 linux/amd64* but anything greater than *1.13* should work.

**Comment by r10r** [comment]
My mistake, please try to use https://github.com/Drachenfels-GmbH/lxc.git  instead of ttps://github.com/lxc/lxc.git for now, the groups feature is not merged yet and needs some rework.

**Comment by r10r** [comment]
so  please try again with 

```
git clone https://github.com/Drachenfels-GmbH/lxc.git
cd lxc
./autogen.sh
./configure --enable-bash=no --enable-tools=no \
  --enable-commands=no --enable-seccomp=yes \
  --enable-capabilities=yes --enable-apparmor=yes
sudo make install

echo /usr/local/lib | sudo tee /etc/ld.so.conf.d/local.conf
sudo ldconfig
```

**Comment by r10r** [comment]
If you look at the README there is a section about the `additionalgids` feature.

https://github.com/Drachenfels-GmbH/crio-lxc#additionalgids

**Comment by r10r** [comment]
> @r10r : which setup did you use for your Debian hosts? Did you manually install the latest Go distribution (I am not tied to Debian, I use Fedora but figured Debian might be better supported as this is what you seem to be using ...)

I'm currently using archlinux for testing.

**Comment by vrubiolo** [comment]
Hi @r10r : many thanks for the quick support, I appreciate that very much!

  - I was seeing the mention of your `go-lxc` repo in the Go build but did not think indeed I needed it to install lxc as well. I will try this out (I had seen the mention about the additional gids which is why I started commenting things out in the `lxc-binding.h` file in the Go build).
  - I will switch to archlinux as well so that we are on the same setup
  - W.r.t to `LXC_DEVEL`, is that set for any checkout of the git repo outside of any tag? I understand this is how they mark a dev tree as opposed to a production/release one but I am not sure how this ends up being set ...

**Comment by r10r** [comment]
> Hi @r10r : many thanks for the quick support, I appreciate that very much!
> 

You're welcome ;)

> * I was seeing the mention of your `go-lxc` repo in the Go build but did not think indeed I needed it to install lxc as well. I will try this out (I had seen the mention about the additional gids which is why I started commenting things out in the `lxc-binding.h` file in the Go build).
> * I will switch to archlinux as well so that we are on the same setup

You can do this - but you don't have to. I prefer archlinux because it has rolling releases, packages are close to upstream and easy to build and the package manager is fast. But since everything required is build from scratch this should work on other distros too.  

> * W.r.t to `LXC_DEVEL`, is that set for any checkout of the git repo outside of any tag? I understand this is how they mark a dev tree as opposed to a production/release one but I am not sure how this ends up being set ...

It's set from `lxc_devel` in `configure.ac` which is changed in release commits. See https://github.com/lxc/lxc/commit/a8565bb4aa15565434127ae008ba994d8f3aab18

**Comment by vrubiolo** [comment]
Thanks for the additional information here.

I went further by moving indeed to your fork of lxc but it still fails to build (I am using archlinux now):
```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../src -fPIC -DPIC -DLXCROOTFSMOUNT=\"/usr/local/lib/lxc/rootfs\" -DLXCPATH=\"/usr/local/var/lib/lxc\" -DLXC_GLOBAL_CONF=\"/usr/local/etc/lxc/lxc.conf\" -DLXCINITDIR=\"/usr/local/libexec\" -DLIBEXECDIR=\"/usr/local/libexec\" -DLXCTEMPLATEDIR=\"/usr/local/share/lxc/templates\" -DLXCTEMPLATECONFIG=\"/usr/local/share/lxc/config\" -DLOGPATH=\"/usr/local/var/log/lxc\" -DLXC_DEFAULT_CONFIG=\"/usr/local/etc/lxc/default.conf\" -DLXC_USERNIC_DB=\"/run/lxc/nics\" -DLXC_USERNIC_CONF=\"/usr/local/etc/lxc/lxc-usernet\" -DDEFAULT_CGROUP_PATTERN=\"\" -DRUNTIME_PATH=\"/run\" -DSBINDIR=\"/usr/local/sbin\" -DAPPARMOR_CACHE_DIR=\"/usr/local/var/cache/lxc/apparmor\" -I ../../src -I ../../src/lxc -I ../../src/lxc/storage -I ../../src/lxc/cgroups -DHAVE_APPARMOR -DHAVE_OPENSSL -DHAVE_SECCOMP -pthread -g -O2 -fdiagnostics-color -Wimplicit-fallthrough=5 -Wcast-align -Wstrict-prototypes -fno-strict-aliasing -fstack-clash-protection -fstack-protector-strong --param=ssp-buffer-size=4 -g -Werror=implicit-function-declaration -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Winit-self -Wunused-but-set-variable -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=return-type -Werror=incompatible-pointer-types -Wformat=2 -Wshadow -Wendif-labels -Werror=overflow -fdiagnostics-show-option -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -fasynchronous-unwind-tables -pipe -fexceptions -Warray-bounds -Wrestrict -Wreturn-local-addr -Wstringop-overflow -Wvla -std=gnu11 -fms-extensions -Werror -MT liblxc_la-log.lo -MD -MP -MF .deps/liblxc_la-log.Tpo -c log.c  -fPIC -DPIC -o .libs/liblxc_la-log.o
log.c:85:20: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
   85 | static const char *lxc_log_get_container_name()
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
log.c: In function ‘lxc_log_get_container_name’:
log.c:85:20: error: old-style function definition [-Werror=old-style-definition]
log.c: In function ‘lxc_log_options_no_override’:
log.c:817:13: error: old-style function definition [-Werror=old-style-definition]
  817 | inline void lxc_log_options_no_override()
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:4167: liblxc_la-log.lo] Error 1
```

My HEAD is at :
```
commit 25579e6ce157b04961e95a7d70c1d0ed469d9888 (HEAD -> master, origin/master, origin/HEAD)
Author: Ruben Jenster <r.jenster@drachenfels.de>
Date:   Thu Nov 5 10:56:19 2020 +0100

    attach: Add groups option to keep additional group IDs.
    
    Signed-off-by: Ruben Jenster <r.jenster@drachenfels.de>
    ```
    
Do you have the same build error? My build log is attached 
[build_log.txt](https://github.com/Drachenfels-GmbH/crio-lxc/files/5857412/build_log.txt)

**Comment by r10r** [comment]
> Do you have the same build error?  I can provide more build log lines if needed

Hmm, no I don't.

**Comment by r10r** [comment]
Can you please attach the complete build ouptut as logfile.

**Comment by r10r** [comment]
Please try to do a `make clean` and rebuild again.

**Comment by r10r** [comment]
I'll upgrade the packages on one of my clusters and try a rebuild.

**Comment by r10r** [comment]
And please provide the output of `uname -a`

**Comment by r10r** [comment]
Ok, after an upgrade I get the same error. 
Give me some time I'll try to find a solution.

**Comment by r10r** [comment]
This works for me

```
git clone https://github.com/Drachenfels-GmbH/lxc.git
cd lxc
./autogen.sh
CFLAGS="-Wno-error=strict-prototypes -Wno-error=old-style-definition" \
./configure --enable-bash=no --enable-tools=no \
  --enable-commands=no --enable-seccomp=yes \
  --enable-capabilities=yes --enable-apparmor=yes
sudo make install

echo /usr/local/lib | sudo tee /etc/ld.so.conf.d/local.conf
sudo ldconfig
```

**Comment by r10r** [comment]
It's the autoconf update that breaks the build.
```
[2021-01-22T18:27:42+0100] [ALPM] upgraded autoconf (2.69-7 -> 2.70-1)
```

After downgrading to `2.69-7`  it builds again without `CFLAGS="-Wno-error=strict-prototypes -Wno-error=old-style-definition"`

**Comment by vrubiolo** [comment]
Hi Ruben and thanks again for the assist. With the updated `CFLAGS` on the `configure` command line, I confirm the build is fine for me now. 

Proceeding to the next steps ...

**Comment by r10r** [comment]
Closing since is setgroups features is upstream now
https://github.com/lxc/lxc/pull/3575
https://github.com/lxc/go-lxc/pull/144
